### ISSUE TITLE
Rename this project/repo?

### ISSUE THREAD

**Issue by umesh-timalsina** [KyleAMoore/Redshift-CNN#30]
This repository also contains code for `Inception` neural network. Should we rename it to be more representative?

**Comment by KyleAMoore** [comment]
That seems prudent. I feel that it needs a name more descriptive than simply "redshift", however, to differentiate it from your original repo. Any suggestions or thoughts on that?

**Comment by umesh-timalsina** [comment]
Yeah. It should not be named `redshift`. we can hold it for now, but `Redshift-CNN` or `redshift-nns` are some of the names I had in mind.

**Comment by KyleAMoore** [comment]
I believe that `Redshift-CNN` is most appropriate. I will change the name to that at noon on Tuesday 4/28 if there are no objections before then.
